version: "3"
services:
  webapp:
    # replace username/repo:tag with your name and image details
    image: mariuscornescu/demo:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5080:80"
    networks:
      - webappnet
networks:
  webappnet:
  